language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "codenote"
  - provider: codedeploy
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    bucket: "codenote"
    key: "codenote"
    application: "codenote"
    deployment_group: "code-note-deploy-group"